[2025-07-08T20:15:31.291+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: daily_sales_report.fetch_sales_data scheduled__2025-07-07T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
